import type { FilaDesglose } from '../../dominio/desglose';

/**
 * LA FOTO DE PRODUCCIÓN POR CANAL QUE SIRVE LA GALERÍA DEL PIPELINE DE VENTAS — literal, no inventada.
 *
 * Medida el 2026-09-14 (~15:40Z) en producción, SÓLO LECTURA, corriendo la consulta EXACTA del
 * tablero de la Escuela con `mesaPorCanal=1` (`consultarCola`: las cinco columnas, sesión supervisora
 * `gsifuentes`, `inicioDeHoy` = medianoche de Lima del 14-sep): el SQL se capturó con el logger de
 * drizzle contra una base local migrada, con los parámetros inlineados, y se corrió en prod adentro
 * de una transacción que se deshace, con las tablas temporales `todo` y `padron` reescritas como CTE
 * (`CREATE TABLE AS` no corre en una transacción de sólo lectura). Filas etapa × ya-le-hablamos ×
 * precio × viva × ventana × para seguir × se calló × luz × nació hoy × canal × tipo, tal cual las
 * devolvió la consulta, generadas desde el CSV (sin transcribir a mano).
 *
 * Existe por el candado 10: una galería que no sirve los valores REALES no es evidencia. Dos fotos:
 * la de 30 días (`rangoGlobal` nulo) y la de «Hoy» (`franjaEn=*` desde la medianoche de Lima). «7 d»
 * no se midió: la galería sirve la de 30 días bajo ese rango, y lo dice en `galeria.tsx`.
 *
 * Cruces verificados sobre estas filas: la suma por etapa de la foto de 30 d coincide con los `conteos`
 * de la misma consulta (interesado 992, sin_respuesta 8543, contactado 440, cotizado 4254, cierre 116).
 */
export const DESGLOSE_POR_CANAL_PROD_2026_09_14: FilaDesglose[] = [
  { etapa: 'cierre', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 14 },
  { etapa: 'cierre', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'cierre', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'cierre', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'cierre', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 45 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: true, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 30 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 6 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: true, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 184 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 11 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'rojo', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 19 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 187 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 6 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'rojo', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 14 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'facebook', tipo: 'comentario', n: 3 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'instagram', tipo: 'comentario', n: 1 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 5 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'facebook', tipo: 'comentario', n: 1 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'facebook', tipo: 'comentario', n: 1 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'contactado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 589 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 75 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'rojo', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 19 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 70 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: true, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1243 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: true, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: true, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 62 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 388 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 8 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'rojo', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 8 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 75 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: true, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1481 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: true, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: true, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 25 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 4 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: true, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 97 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: true, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 36 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: true, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: true, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 24 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: true, luz: 'verde', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 4 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 8 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: true, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 24 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'rojo', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'facebook', tipo: 'comentario', n: 81 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'facebook', tipo: 'mensaje', n: 132 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'instagram', tipo: 'comentario', n: 20 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 121 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'facebook', tipo: 'comentario', n: 74 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'facebook', tipo: 'mensaje', n: 4 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'landing', tipo: 'lead', n: 78 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 16 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'rojo', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'facebook', tipo: 'comentario', n: 15 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'facebook', tipo: 'mensaje', n: 8 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'instagram', tipo: 'comentario', n: 2 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 14 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'facebook', tipo: 'comentario', n: 86 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'instagram', tipo: 'comentario', n: 26 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'facebook', tipo: 'comentario', n: 2 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'facebook', tipo: 'comentario', n: 43 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'instagram', tipo: 'comentario', n: 2 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: true, canal: 'facebook', tipo: 'comentario', n: 1 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'facebook', tipo: 'comentario', n: 10 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'instagram', tipo: 'comentario', n: 1 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'landing', tipo: 'lead', n: 1 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'facebook', tipo: 'mensaje', n: 2 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 5 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'interesado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'facebook', tipo: 'mensaje', n: 1 },
  { etapa: 'interesado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 190 },
  { etapa: 'interesado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 17 },
  { etapa: 'interesado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'rojo', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 5 },
  { etapa: 'interesado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 12 },
  { etapa: 'interesado', yaLeHablamos: true, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 13 },
  { etapa: 'interesado', yaLeHablamos: true, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'interesado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 4 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 883 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 6 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 806 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'facebook', tipo: 'mensaje', n: 1 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 497 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1867 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 25 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 4313 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 135 },
];

/** Los conteos por etapa del mismo pedido de 30 d (todos los canales). */
export const CONTEOS_PROD_2026_09_14: Record<string, number> = {"interesado": 992, "sin_respuesta": 8543, "contactado": 440, "cotizado": 4254, "cierre": 116};

/** La misma consulta con «Hoy» puesto (`franjaEn=*`, desde la medianoche de Lima del 14-sep-2026). */
export const DESGLOSE_POR_CANAL_HOY_PROD_2026_09_14: FilaDesglose[] = [
  { etapa: 'cierre', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'cierre', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 6 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'facebook', tipo: 'comentario', n: 1 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'contactado', yaLeHablamos: true, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 12 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 4 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: true, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 74 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: true, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 10 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 48 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 8 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: true, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 95 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 18 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 4 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: true, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 62 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: true, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 36 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: true, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 18 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: false, seCallo: true, luz: 'verde', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 4 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 5 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: false, ventana: true, paraSeguir: true, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 13 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'cotizado', yaLeHablamos: true, precio: true, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'rojo', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'facebook', tipo: 'comentario', n: 2 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: false, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: true, canal: 'facebook', tipo: 'comentario', n: 1 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 2 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'interesado', yaLeHablamos: false, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'verde', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'interesado', yaLeHablamos: true, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 5 },
  { etapa: 'interesado', yaLeHablamos: true, precio: false, viva: true, ventana: true, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 5 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: false, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 3 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 1 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 28 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: false, seCallo: false, luz: 'gris', nacioHoy: true, canal: 'whatsapp', tipo: 'mensaje', n: 25 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'ambar', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 21 },
  { etapa: 'sin_respuesta', yaLeHablamos: true, precio: true, viva: false, ventana: false, paraSeguir: true, seCallo: false, luz: 'gris', nacioHoy: false, canal: 'whatsapp', tipo: 'mensaje', n: 71 },
];

/** Los conteos por etapa de «Hoy» (todos los canales). */
export const CONTEOS_HOY_PROD_2026_09_14: Record<string, number> = {"interesado": 992, "sin_respuesta": 8543, "contactado": 440, "cotizado": 4254, "cierre": 116};
